name: generator
on:
  pull_request:
jobs:
  generate:
    name: generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: actions/checkout@v3
      - run: make generate

      - name: Commit changes
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            git config --global user.name "GitHub Actions
            git config --global user.email "l.a.r.p@yandex.ru"
            git commit -a -m "Updated converts.yaml"

      - name: Push changes
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: git push
